# Generated by Django 5.1.7 on 2025-03-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_temporaryregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryregistration",
            name="totp_secret",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
