# Generated by Django 5.1.7 on 2025-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_artist_genre_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="program",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="year",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
