# Generated by Django 5.1.7 on 2025-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_userprofile_first_name_userprofile_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="year",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="term",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
