# Generated by Django 5.1.7 on 2025-03-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_userprofile_year_userprofile_term"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="program",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="faculty",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
